# Generated by Django 5.2.5 on 2025-08-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('feature1', models.CharField(max_length=100)),
                ('feature1_range', models.CharField(max_length=100)),
                ('feature2', models.CharField(max_length=100)),
                ('feature2_range', models.CharField(max_length=100)),
                ('demand', models.CharField(max_length=50)),
                ('demand_coeff', models.DecimalField(decimal_places=2, max_digits=4)),
                ('local_supply', models.CharField(max_length=50)),
                ('supply_coeff', models.DecimalField(decimal_places=2, max_digits=4)),
                ('market_price', models.CharField(max_length=50)),
                ('price_coeff', models.DecimalField(decimal_places=2, max_digits=4)),
                ('price_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('local_price_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('local_price_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('market_relation', models.CharField(max_length=100)),
                ('range_num1', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('range_num2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('valuation_coeff', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('valuation', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
